version: '3'
services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/code/
    ports:
      - "8080:8080"
    env_file: 
      - ./frontend/.env

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/code/
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file: 
      - ./backend/.env

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    hostname: database

volumes:
  db-data:
