name: Deploy to AWS

on:
  push:
    branches:
      - main
      - auto-deploy

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423446384:role/github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push frontend Docker image
        env:
          FRONTEND_IMAGE: public.ecr.aws/m8r7m6j8/portfolio-frontend-1:latest
        run: |
          docker buildx build --platform linux/amd64 -t $FRONTEND_IMAGE --push frontend

      - name: Build, tag, and push backend Docker image
        env:
          BACKEND_IMAGE: public.ecr.aws/m8r7m6j8/portfolio-backend-1:latest
        run: |
          docker buildx build --platform linux/amd64 -t $BACKEND_IMAGE --push backend