name: Deploy to AWS

on:
  push:
    branches:
      - main
      - auto-deploy

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY_FRONTEND: portfolio-frontend-1
      ECR_REPOSITORY_BACKEND: portfolio-backend-1
      FRONTEND_IMAGE: public.ecr.aws/m8r7m6j8/portfolio-frontend-1:latest
      BACKEND_IMAGE: public.ecr.aws/m8r7m6j8/portfolio-backend-1:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423446384:role/github-actions-role
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build frontend Docker image
        run: |
          docker buildx build --platform linux/amd64 -t portfolio-frontend-1 frontend --load

      - name: List Docker images
        run: docker images

      - name: Tag and push frontend Docker image
        run: |
          docker tag portfolio-frontend-1:latest $FRONTEND_IMAGE
          docker push $FRONTEND_IMAGE

      - name: Build and push backend Docker image
        run: |
          docker buildx build --platform linux/amd64 -t portfolio-backend-1 backend --load
          docker tag portfolio-backend-1:latest $BACKEND_IMAGE
          docker push $BACKEND_IMAGE