name: Test Frontend

on:
    pull_request:
    push:
        branches:
            - main
            - testing

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Install wasm-pack
              run: cargo install wasm-pack

            - name: Build and test
              working-directory: ./frontend  
              # run: cargo test
              run: wasm-pack test --node