name: Test Backend

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Build and test
              working-directory: ./backend
              run: cargo test
              env: 
                DATABASE_URL: postgresql://postgres:mysecretpassword@localhost:5432/postgres
                JWT_SECRET: mysecret


