name: Test Frontend

on:
    pull_request:
    push:
        branches:
            - main
            - testing
            - auto-deploy

jobs:
    test:
        runs-on: ubuntu-ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                target: wasm32-unknown-unknown

            - name: Install wasm-pack
              uses: jetli/wasm-pack-action@v0.4.0

            - name: Setup Chrome and ChromeDriver
              uses: browser-actions/setup-chrome@v1
              with:
                chrome-version: stable
                install-chromedriver: true
                install-dependencies: true

            - name: Build and test
              working-directory: ./frontend
              run: wasm-pack test --chrome --headless